url: https://lukekorth.com
title: Luke Korth
email: website@lukekorth.com
description: Personal photography portfolio and occasional writings.
root: /
permalink: /journal/:title/

include: ['_redirects']
exclude: ['Gemfile*', 'Rakefile', 'README.md', '**/README.md']
host: 0.0.0.0

plugins: [jekyll-sitemap]

sass:
  style: compressed
