# Site settings
url: http://lukekorth.com
title: LukeKorth.com
description: "Luke Korth's personal blog"
author: Luke Korth
email: blog@lukekorth.com

permalink: /:categories/:title
exclude: ["Rakefile", "README.md"]
paginate: 3

# only_first_p plugin
only_first_p:
  show_read_more_link: false

asset_pipeline:
  gzip: true