url: https://lukekorth.com
title: Luke Korth
email: blog@lukekorth.com
description: A personal blog about technology, open source and photography.
root: /
permalink: /blog/:title/

exclude: ['Gemfile*', 'README.md', '**/README.md', 'firebase.json']

plugins: [jekyll-paginate, jekyll-sitemap]

sass:
  style: compressed

markdown: redcarpet
redcarpet:
  extentions:
    - hard_wrap
    - fenced_code_blocks
    - autolink
    - with_toc_data
    - strikethrough

paginate: 5                     # Posts per page on the blog index
paginate_path: blog/:num        # Path structure for pagination URLs eg. /blog/page/2/
recent_posts: 5                 # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

# 500px
500px_consumer_key_file: .500px-consumer-key

# Disqus Comments
disqus_short_name: lukekorth
disqus_url: https://lukekorth.com

# Gravatar
gravatar_email: blog@lukekorth.com

# GitHub
github_username: lkorth

# Twitter sharing
twitter_username: lukekorth

# Instagram
instagram_access_token: .instagram-access-token
