# Site settings
url: http://lukekorth.com
title: LukeKorth.com
description: "Luke Korth's personal blog"
author: Luke Korth
email: blog@lukekorth.com

permalink: /:categories/:title
exclude: ["Rakefile", "README.md"]
paginate: 3

# only_first_p plugin
only_first_p:
    show_read_more_link: false

# jekyll-asset_bundler plugin
asset_bundler:
  compress:
    js: closure -o :outfile :infile
    css: yuicompressor -o :outfile :infile
  remove_bundled: true
  markup_templates:
    js: "<script src='{{url}}'></script>\n"
    css: "<link rel='stylesheet' href='{{url}}' />\n"