# Default date format is "ordinal" (resulting in "July 22nd 2007")
# You can customize the format as defined in
# http://www.ruby-doc.org/core-1.9.2/Time.html#method-i-strftime
# Additionally, %o will give you the ordinal representation of the day
date_format: "ordinal"

# ---------- #
#   Jekyll   #
# ---------- #

plugins: _plugins
code_dir: downloads/code
category_dir: blog/categories
lsi: false
recent_posts: 5                 # Posts in the sidebar Recent Posts section

# list each of the sidebar modules you want to include, in the order you want them to appear.
# To add custom asides, create files in _includes/custom/asides/ and add them to the list like 'custom/asides/custom_aside_name.html'
default_asides: [asides/googleplus.html, asides/recent_posts.html, custom/asides/tag_cloud.html, custom/asides/page_view.html]

exclude:
  - google-api-private-key.p12

# gems:
#   - jekyll-sitemap

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

# Google Plus Profile
# Just add author information to search results
googleplus_user: +LukeKorth
googleplus_hidden: true

# Google Analytics
google_analytics_tracking_id: UA-23752726-1

# Google Analytics page views
# page-view:
#   service_account_email: 286207001701-qi7icmu1s4o49k8tt0b2m9hprjfiv9q1@developer.gserviceaccount.com
#   key_file: .google-api-private-key.p12
#   key_secret: notasecret
#   profileID: ga:46718938
#   start: 7 years ago   # Beginning of report
#   end: now             # End of report
#   metric: ga:pageviews # Metric code
