url: https://lukekorth.com
title: Luke Korth
author: Luke Korth
email: blog@lukekorth.com
description: >
  My blog about the apps and projects I'm working on and anything I find interesting.
root: /
permalink: /blog/:title/

gems: [jekyll-paginate]

markdown: redcarpet
redcarpet:
  extentions:
    - hard_wrap
    - fenced_code_blocks
    - autolink
    - with_toc_data
    - strikethrough

paginate: 5                     # Posts per page on the blog index
paginate_path: blog/:num        # Path structure for pagination URLs eg. /blog/page/2/
recent_posts: 5                 # Posts in the sidebar Recent Posts section
excerpt_link: "Read on &rarr;"  # "Continue reading" link text at the bottom of excerpted articles

# 500px
500px_consumer_key_file: .500px-consumer-key

# Disqus Comments
disqus_short_name: lukekorth

# Gravatar
gravatar_email: blog@lukekorth.com

# GitHub post revision history
github_username: lkorth
github_user: lkorth
github_repo: lukekorth.com

